---
# tasks file for vector
- name: Download repo
# doc: https://vector.dev/docs/setup/installation/package-managers/yum/
  ansible.builtin.get_url:
    url: "https://setup.vector.dev"
    dest: "./vector"
    mode: "0755"

- name: Add vector repo
  become: true
  ansible.builtin.shell: "./vector > /vector.txt"
  args:
    creates: "/vector.txt"

- name: Install vector
  become: true
  ansible.builtin.yum:
    name: vector


- name: Create vector service
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true

- name: Create vector configuration
  become: true
  ansible.builtin.template:
    src: vector.config.j2
    dest: "{{ vector_config_dir }}/{{ vector_config_file }}"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
